# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param length_of_chains the number of samples
#' @param from_point how many number ahead are to abandon
#' @param a,b the shape of distribution Y = beta(x+a,n-x+b)
#' @param x_range = n the X values uses in distribution X = Binomial(n, y)
#' @param mu_x,mu_y the expectation of X and Y
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' ZC <- cp_gibbsC()
#' }
#' @export
cp_gibbsC <- function(length_of_chains = 1e4L, from_point = 1000L, a = 1L, b = 1L, x_range = 10L, mu_x = -1, mu_y = -1) {
    .Call('_StatComp21047_cp_gibbsC', PACKAGE = 'StatComp21047', length_of_chains, from_point, a, b, x_range, mu_x, mu_y)
}

